# Generated by Django 4.2.11 on 2025-03-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_ejecucionmatriz_conforme"),
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="Empresa",
        ),
        migrations.AddField(
            model_name="customuser",
            name="Empresa",
            field=models.ManyToManyField(
                blank=True,
                related_name="usuarios",
                through="users_app.UserCompany",
                to="myapp.empresa",
            ),
        ),
    ]
