"""
Django settings for ProjectFrameworksas project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""



import os
from pathlib import Path
import environ
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Esto debería apuntar a D:\AAA_Framework\ProjectFrameworksas
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicializa environ. Puedes definir tipos y valores por defecto aquí si es necesario.
# Por ejemplo, para DJANGO_DEBUG, si no se encuentra, por defecto será False.
env = environ.Env(
    DJANGO_DEBUG=(bool, False)
)

# Construye la ruta explícita al archivo .env
# Esto debería ser D:\AAA_Framework\ProjectFrameworksas\.env
env_file_path = BASE_DIR / '.env'

# Imprime mensajes de depuración para verificar la ruta y si se encuentra el archivo
#print(f"DEBUG: settings.py - BASE_DIR es: {BASE_DIR}")
#print(f"DEBUG: settings.py - Intentando leer .env desde: {env_file_path}")

# Intenta leer el archivo .env desde la ruta explícita.
# Es crucial que esto ocurra ANTES de intentar acceder a las variables con env('VARIABLE')
if env_file_path.exists():
    environ.Env.read_env(str(env_file_path))
    #print(f"DEBUG: settings.py - Archivo .env encontrado y leído desde {env_file_path}")
else:
    #print(f"ADVERTENCIA: settings.py - Archivo .env NO encontrado en {env_file_path}. Las variables de entorno deben establecerse externamente.")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-&&!qmb&f85=uyc7!_ize!lb&!q$@)d0nc0)im_31$in@x*v7r^'
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = env('DJANGO_DEBUG')


ALLOWED_HOSTS = ["*" ,"*.up.railway.app"]

# Añade tu dominio de Railway aquí para la verificación CSRF
CSRF_TRUSTED_ORIGINS = [
    'https://frameworksasgestreq-production.up.railway.app'
]

# Application definition

INSTALLED_APPS = [
    "semantic_admin",
    "semantic_forms",
    "django_select2",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "myapp",
    "import_export",
    "users_app",
    
   
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", 
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'myapp.middleware.CompanyMiddleware',
    'myapp.middleware.ErrorHandlingMiddleware',
   
]

ROOT_URLCONF = "ProjectFrameworksas.urls"



TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'), # this is for admin templates
            #os.path.join(BASE_DIR, 'users_app/templates'), # this is for users_app templates
            #os.path.join(BASE_DIR, 'myapp/templates'), # this is for myapp templates
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            'builtins': [
                'semantic_forms.templatetags.semantic_forms',
            ],
        },
    },
]

WSGI_APPLICATION = "ProjectFrameworksas.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases




DATABASES = {
      'default': dj_database_url.config(
        # dj-database-url buscará automáticamente la variable de entorno DATABASE_URL.
        # No es necesario usar env() aquí para la URL de la base de datos.
        conn_max_age=600 # Opcional: mantiene las conexiones abiertas por 10 minutos
    )
 }





#DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.sqlite3",
#        "NAME": BASE_DIR / "databasen1.sqlite3",
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "es-CO"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/





STATIC_URL = '/staticfiles/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] # Comentado si no tienes una carpeta static/ a nivel de proyecto
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage' # Para que WhiteNoise sirva archivos estáticos eficientemente

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles") # New line
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
# redespliegue


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = 'users_app.CustomUser'  # app_name.ModelName


LOGIN_REDIRECT_URL = "home"
LOGIN_URL = "users_app:login" # change this line
LOGOUT_REDIRECT_URL = "users_app:logout"
