# Generated by Django 4.2.11 on 2025-04-30 21:22

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EjecucionMatriz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "porcentaje_cumplimiento",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "evidencia_cumplimiento",
                    models.FileField(
                        blank=True, null=True, upload_to="evidencia_legal/"
                    ),
                ),
                (
                    "responsable",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                ("fecha_ejecucion", models.DateField(blank=True, null=True)),
                ("resultado_evaluacion", models.TextField(blank=True, null=True)),
                (
                    "ejecucion",
                    models.BooleanField(default=False, verbose_name="Ejecutado"),
                ),
                (
                    "conforme",
                    models.CharField(
                        choices=[("Si", "Sí"), ("No", "No")], default="No", max_length=2
                    ),
                ),
                (
                    "razon_no_conforme",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Obligatorio si el estado es 'No conforme'.",
                        null=True,
                        verbose_name="Razón No Conforme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejecucion del Plan",
                "verbose_name_plural": "Ejecucion de los Planes",
                "ordering": ["matriz", "requisito", "plan"],
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "codigoempresa",
                    models.CharField(
                        default="", max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("nombreempresa", models.CharField(default="", max_length=150)),
                ("direccion", models.CharField(default="", max_length=200)),
                (
                    "telefono",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logos_empresa/"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["nombreempresa"],
            },
        ),
        migrations.CreateModel(
            name="Industria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Industria",
                "verbose_name_plural": "Industrias",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código ISO 3166-1 alpha-2 del país (ej. CO, MX, US)",
                        max_length=2,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pais",
                "verbose_name_plural": "Paises",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="RequisitoLegal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tema", models.CharField(max_length=50)),
                ("entidad_que_emite", models.CharField(max_length=255)),
                ("jerarquia_de_la_norma", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=50)),
                ("fecha", models.DateField(verbose_name="Fecha de Vigencia")),
                (
                    "tiempo_validacion",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Número de días hábiles (según país) estimados o requeridos para validar.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tiempo de Validación (Días Hábiles)",
                    ),
                ),
                ("articulo_aplicable", models.TextField()),
                ("Obligacion", models.TextField()),
                ("proceso_que_aplica", models.CharField(max_length=255)),
                (
                    "tipo_requisito",
                    models.CharField(
                        choices=[
                            ("Local", "Local"),
                            ("Externo", "Externo"),
                            ("Ambos", "Ambos"),
                        ],
                        default="Local",
                        max_length=10,
                    ),
                ),
                (
                    "periodicidad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Diaria", "Diaria"),
                            ("Semanal", "Semanal"),
                            ("Quincenal", "Quincenal"),
                            ("Mensual", "Mensual"),
                            ("Bimestral", "Bimestral"),
                            ("Trimestral", "Trimestral"),
                            ("Semestral", "Semestral"),
                            ("Anual", "Anual"),
                            ("Unica", "Única"),
                            ("Otro", "Otro"),
                        ],
                        help_text="Periodicidad con la que se suele evaluar o revisar este requisito.",
                        max_length=20,
                        null=True,
                        verbose_name="Periodicidad Sugerida/Evaluación",
                    ),
                ),
                (
                    "industria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.industria",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.pais",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisito Legal",
                "verbose_name_plural": "Requisitos Legales",
                "ordering": ["tema", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="Nombre de la Sede"),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Dirección"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email de Contacto",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción Adicional"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sedes",
                        to="myapp.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
                "ordering": ["empresa__nombreempresa", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="RequisitosPorEmpresa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.empresa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisitos Por Empresa",
                "verbose_name_plural": "Requisitos Por Empresa",
                "ordering": ["empresa__nombreempresa", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="RequisitoPorEmpresaDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion_cumplimiento", models.TextField(blank=True, null=True)),
                (
                    "periodicidad",
                    models.CharField(
                        choices=[
                            ("Diaria", "Diaria"),
                            ("Semanal", "Semanal"),
                            ("Quincenal", "Quincenal"),
                            ("Mensual", "Mensual"),
                            ("Bimestral", "Bimestral"),
                            ("Trimestral", "Trimestral"),
                            ("Semestral", "Semestral"),
                            ("Anual", "Anual"),
                            ("Unica", "Única"),
                            ("Otro", "Otro"),
                        ],
                        default="Mensual",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateField(default=django.utils.timezone.now)),
                (
                    "tiempo_validacion",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Número de días hábiles (según país del requisito) para validar. Usado para calcular Fecha Final.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tiempo de Validación (Días Hábiles)",
                    ),
                ),
                (
                    "fecha_final",
                    models.DateField(
                        blank=True,
                        editable=False,
                        help_text="Calculada automáticamente basada en Fecha Inicio, Días Hábiles y País del Requisito.",
                        null=True,
                        verbose_name="Fecha Final Estimada (Días Hábiles)",
                    ),
                ),
                (
                    "matriz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="myapp.requisitosporempresa",
                    ),
                ),
                (
                    "requisito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.requisitolegal",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.sede",
                        verbose_name="Sede de Aplicación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisito Por Empresa Detalle",
                "verbose_name_plural": "Requisitos Por Empresa Detalle",
                "ordering": ["matriz", "requisito"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "periodicidad",
                    models.CharField(
                        choices=[
                            ("Diaria", "Diaria"),
                            ("Semanal", "Semanal"),
                            ("Quincenal", "Quincenal"),
                            ("Mensual", "Mensual"),
                            ("Bimestral", "Bimestral"),
                            ("Trimestral", "Trimestral"),
                            ("Semestral", "Semestral"),
                            ("Anual", "Anual"),
                            ("Unica", "Única"),
                            ("Otro", "Otro"),
                        ],
                        default="Mensual",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateField(default=datetime.date.today)),
                (
                    "fecha_proximo_cumplimiento",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de Cumplimiento Programada",
                    ),
                ),
                (
                    "descripcion_periodicidad",
                    models.TextField(
                        blank=True,
                        help_text="Requerido si la periodicidad es 'Otro'.",
                        null=True,
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Año del Plan")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.empresa"
                    ),
                ),
                (
                    "requisito_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.requisitoporempresadetalle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan (Tarea)",
                "verbose_name_plural": "Planes (Tareas)",
                "ordering": [
                    "empresa__nombreempresa",
                    "year",
                    "requisito_empresa",
                    "fecha_proximo_cumplimiento",
                ],
            },
        ),
    ]
