# Generated by Django 4.2.11 on 2025-03-16 01:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "codigoempresa",
                    models.CharField(
                        default="", max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("nombreempresa", models.CharField(default="", max_length=150)),
                ("direccion", models.CharField(default="", max_length=200)),
                (
                    "telefono",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.CreateModel(
            name="Industria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Industria",
                "verbose_name_plural": "Industrias",
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("codigo", models.CharField(max_length=5, unique=True)),
            ],
            options={
                "verbose_name": "Pais",
                "verbose_name_plural": "Paises",
            },
        ),
        migrations.CreateModel(
            name="RequisitoLegal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tema", models.CharField(max_length=50)),
                ("entidad_que_emite", models.CharField(max_length=255)),
                ("jerarquia_de_la_norma", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=50)),
                ("fecha", models.DateField()),
                ("articulo_aplicable", models.TextField()),
                ("Obligacion", models.TextField()),
                ("proceso_que_aplica", models.CharField(max_length=255)),
                (
                    "tipo_requisito",
                    models.CharField(
                        choices=[
                            ("Local", "Local"),
                            ("Externo", "Externo"),
                            ("Ambos", "Ambos"),
                        ],
                        default="Local",
                        max_length=10,
                    ),
                ),
                (
                    "industria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.industria",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.pais",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisito Legal",
                "verbose_name_plural": "Requisitos Legales",
            },
        ),
        migrations.CreateModel(
            name="RequisitosPorEmpresa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.empresa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisitos Por Empresa",
                "verbose_name_plural": "Requisitos Por Empresa",
            },
        ),
        migrations.CreateModel(
            name="RequisitoPorEmpresaDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion_cumplimiento", models.TextField(blank=True, null=True)),
                (
                    "periodicidad",
                    models.CharField(
                        choices=[
                            ("Diaria", "Diaria"),
                            ("Semanal", "Semanal"),
                            ("Quincenal", "Quincenal"),
                            ("Mensual", "Mensual"),
                            ("Bimestral", "Bimestral"),
                            ("Trimestral", "Trimestral"),
                            ("Semestral", "Semestral"),
                            ("Anual", "Anual"),
                            ("Unica", "Única"),
                            ("Otro", "Otro"),
                        ],
                        default="Mensual",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateField(default=datetime.date.today)),
                (
                    "matriz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.requisitosporempresa",
                    ),
                ),
                (
                    "requisito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.requisitolegal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisito Por Empresa Detalle",
                "verbose_name_plural": "Requisitos Por Empresa Detalle",
                "unique_together": {("matriz", "requisito")},
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "periodicidad",
                    models.CharField(
                        choices=[
                            ("Diaria", "Diaria"),
                            ("Semanal", "Semanal"),
                            ("Quincenal", "Quincenal"),
                            ("Mensual", "Mensual"),
                            ("Bimestral", "Bimestral"),
                            ("Trimestral", "Trimestral"),
                            ("Semestral", "Semestral"),
                            ("Anual", "Anual"),
                            ("Unica", "Única"),
                            ("Otro", "Otro"),
                        ],
                        default="Mensual",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateField(default=datetime.date.today)),
                ("fecha_proximo_cumplimiento", models.DateField(blank=True, null=True)),
                ("descripcion_periodicidad", models.TextField(blank=True, null=True)),
                ("year", models.PositiveIntegerField()),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.empresa"
                    ),
                ),
                (
                    "requisito_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.requisitoporempresadetalle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Planes",
            },
        ),
        migrations.CreateModel(
            name="EjecucionMatriz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "porcentaje_cumplimiento",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "evidencia_cumplimiento",
                    models.FileField(
                        blank=True, null=True, upload_to="evidencia_legal/"
                    ),
                ),
                (
                    "responsable",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                ("fecha_ejecucion", models.DateField(blank=True, null=True)),
                ("resultado_evaluacion", models.TextField(blank=True, null=True)),
                ("ejecucion", models.BooleanField(default=False)),
                ("conforme", models.BooleanField(default=False)),
                ("razon_no_conforme", models.TextField(blank=True, null=True)),
                (
                    "matriz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.requisitosporempresa",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.plan",
                    ),
                ),
                (
                    "requisito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.requisitolegal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejecucion del Plan",
                "verbose_name_plural": "Ejecucion de los Planes",
                "unique_together": {("matriz", "requisito", "plan")},
            },
        ),
    ]
