# Generated by Django 4.2.11 on 2025-04-30 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="responsable_ejecucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planes_asignados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable Ejecución",
            ),
        ),
        migrations.AddField(
            model_name="ejecucionmatriz",
            name="matriz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.requisitosporempresa",
            ),
        ),
        migrations.AddField(
            model_name="ejecucionmatriz",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.plan",
            ),
        ),
        migrations.AddField(
            model_name="ejecucionmatriz",
            name="requisito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.requisitolegal"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sede",
            unique_together={("empresa", "nombre")},
        ),
        migrations.AddIndex(
            model_name="requisitoporempresadetalle",
            index=models.Index(
                fields=["matriz", "requisito"], name="myapp_requi_matriz__6510c5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requisitoporempresadetalle",
            unique_together={("matriz", "requisito", "sede")},
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(
                fields=["empresa", "year"], name="myapp_plan_empresa_f703ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(
                fields=["requisito_empresa"], name="myapp_plan_requisi_9a5ebe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(
                fields=["year", "fecha_proximo_cumplimiento"],
                name="myapp_plan_year_8d7a40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(
                fields=["responsable_ejecucion"], name="myapp_plan_respons_4f09d1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plan",
            unique_together={
                ("requisito_empresa", "year", "fecha_proximo_cumplimiento")
            },
        ),
        migrations.AddIndex(
            model_name="ejecucionmatriz",
            index=models.Index(
                fields=["matriz", "requisito", "plan"],
                name="myapp_ejecu_matriz__81ac72_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ejecucionmatriz",
            unique_together={("matriz", "requisito", "plan")},
        ),
    ]
