# Generated by Django 4.2.11 on 2025-03-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ejecucionmatriz",
            name="conforme",
            field=models.CharField(
                choices=[("Si", "Sí"), ("No", "No")], default="No", max_length=2
            ),
        ),
    ]
