# Generated by Django 4.2.11 on 2025-04-08 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_ejecucionmatriz_conforme"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisitolegal",
            name="tiempo_validacion",
            field=models.DurationField(
                blank=True,
                help_text="Tiempo estimado o requerido para validar el cumplimiento del requisito (ej. '30 days', '6 months').",
                null=True,
                verbose_name="Tiempo de Validación",
            ),
        ),
        migrations.AddField(
            model_name="requisitoporempresadetalle",
            name="fecha_final",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="Fecha calculada automáticamente basada en la Fecha de Inicio y el Tiempo de Validación.",
                null=True,
                verbose_name="Fecha Final Estimada",
            ),
        ),
        migrations.AddField(
            model_name="requisitoporempresadetalle",
            name="tiempo_validacion",
            field=models.DurationField(
                blank=True,
                help_text="Tiempo estimado o requerido para validar el cumplimiento del requisito (ej. '30 days', '6 months'). Se usará para calcular la Fecha Final.",
                null=True,
                verbose_name="Tiempo de Validación",
            ),
        ),
        migrations.AlterField(
            model_name="ejecucionmatriz",
            name="razon_no_conforme",
            field=models.TextField(
                default=".",
                error_messages={"required": "Por favor, ingrese una razón."},
            ),
        ),
        migrations.AlterField(
            model_name="requisitoporempresadetalle",
            name="fecha_inicio",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
