# Generated by Django 4.2.11 on 2025-04-28 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_requisitolegal_tiempo_validacion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sede",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="Nombre de la Sede"),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Dirección"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email de Contacto",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción Adicional"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sedes",
                        to="myapp.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
                "ordering": ["empresa", "nombre"],
                "unique_together": {("empresa", "nombre")},
            },
        ),
    ]
