# Generated by Django 4.2.11 on 2025-04-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_sede"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisitolegal",
            name="periodicidad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Diaria", "Diaria"),
                    ("Semanal", "Semanal"),
                    ("Quincenal", "Quincenal"),
                    ("Mensual", "Mensual"),
                    ("Bimestral", "Bimestral"),
                    ("Trimestral", "Trimestral"),
                    ("Semestral", "Semestral"),
                    ("Anual", "Anual"),
                    ("Unica", "Única"),
                    ("Otro", "Otro"),
                ],
                help_text="Periodicidad con la que se suele evaluar o revisar este requisito.",
                max_length=20,
                null=True,
                verbose_name="Periodicidad Sugerida/Evaluación",
            ),
        ),
        migrations.AlterField(
            model_name="requisitolegal",
            name="fecha",
            field=models.DateField(verbose_name="Fecha de Vigencia"),
        ),
    ]
