# Generated by Django 4.2.11 on 2025-04-30 02:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_requisitolegal_periodicidad_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ejecucionmatriz",
            options={
                "ordering": ["matriz", "requisito", "plan"],
                "verbose_name": "Ejecucion del Plan",
                "verbose_name_plural": "Ejecucion de los Planes",
            },
        ),
        migrations.AlterModelOptions(
            name="empresa",
            options={
                "ordering": ["nombreempresa"],
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.AlterModelOptions(
            name="industria",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Industria",
                "verbose_name_plural": "Industrias",
            },
        ),
        migrations.AlterModelOptions(
            name="pais",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Pais",
                "verbose_name_plural": "Paises",
            },
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={
                "ordering": ["empresa__nombreempresa", "year", "requisito_empresa"],
                "verbose_name": "Plan",
                "verbose_name_plural": "Planes",
            },
        ),
        migrations.AlterModelOptions(
            name="requisitolegal",
            options={
                "ordering": ["tema", "numero"],
                "verbose_name": "Requisito Legal",
                "verbose_name_plural": "Requisitos Legales",
            },
        ),
        migrations.AlterModelOptions(
            name="requisitoporempresadetalle",
            options={
                "ordering": ["matriz", "requisito"],
                "verbose_name": "Requisito Por Empresa Detalle",
                "verbose_name_plural": "Requisitos Por Empresa Detalle",
            },
        ),
        migrations.AlterModelOptions(
            name="requisitosporempresa",
            options={
                "ordering": ["empresa__nombreempresa", "nombre"],
                "verbose_name": "Requisitos Por Empresa",
                "verbose_name_plural": "Requisitos Por Empresa",
            },
        ),
        migrations.AlterModelOptions(
            name="sede",
            options={
                "ordering": ["empresa__nombreempresa", "nombre"],
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
            },
        ),
        migrations.AlterField(
            model_name="ejecucionmatriz",
            name="ejecucion",
            field=models.BooleanField(default=False, verbose_name="Ejecutado"),
        ),
        migrations.AlterField(
            model_name="ejecucionmatriz",
            name="razon_no_conforme",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Obligatorio si el estado es 'No conforme'.",
                null=True,
                verbose_name="Razón No Conforme",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos_empresa/"),
        ),
        migrations.AlterField(
            model_name="pais",
            name="codigo",
            field=models.CharField(
                help_text="Código ISO 3166-1 alpha-2 del país (ej. CO, MX, US)",
                max_length=2,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="descripcion_periodicidad",
            field=models.TextField(
                blank=True,
                help_text="Requerido si la periodicidad es 'Otro'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="year",
            field=models.PositiveIntegerField(verbose_name="Año del Plan"),
        ),
        migrations.AlterField(
            model_name="requisitolegal",
            name="industria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.industria",
            ),
        ),
        migrations.AlterField(
            model_name="requisitolegal",
            name="pais",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.pais",
            ),
        ),
        migrations.AlterField(
            model_name="requisitolegal",
            name="tiempo_validacion",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Número de días hábiles (según país) estimados o requeridos para validar.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Tiempo de Validación (Días Hábiles)",
            ),
        ),
        migrations.AlterField(
            model_name="requisitoporempresadetalle",
            name="fecha_final",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="Calculada automáticamente basada en Fecha Inicio, Días Hábiles y País del Requisito.",
                null=True,
                verbose_name="Fecha Final Estimada (Días Hábiles)",
            ),
        ),
        migrations.AlterField(
            model_name="requisitoporempresadetalle",
            name="matriz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="myapp.requisitosporempresa",
            ),
        ),
        migrations.AlterField(
            model_name="requisitoporempresadetalle",
            name="tiempo_validacion",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Número de días hábiles (según país del requisito) para validar. Usado para calcular Fecha Final.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Tiempo de Validación (Días Hábiles)",
            ),
        ),
        migrations.AddIndex(
            model_name="ejecucionmatriz",
            index=models.Index(
                fields=["matriz", "requisito", "plan"],
                name="myapp_ejecu_matriz__81ac72_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(
                fields=["empresa", "year"], name="myapp_plan_empresa_f703ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(
                fields=["requisito_empresa"], name="myapp_plan_requisi_9a5ebe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requisitoporempresadetalle",
            index=models.Index(
                fields=["matriz", "requisito"], name="myapp_requi_matriz__6510c5_idx"
            ),
        ),
    ]
