# Generated by Django 4.2.11 on 2025-05-02 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_plan_options_plan_responsable_ejecucion_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="plan",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="plan",
            name="sede",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.sede",
                verbose_name="Sede Aplicable",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plan",
            unique_together={
                ("requisito_empresa", "year", "fecha_proximo_cumplimiento", "sede")
            },
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(fields=["sede"], name="myapp_plan_sede_id_2c3041_idx"),
        ),
    ]
