# Generated by Django 4.2.11 on 2025-05-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_plan_unique_together_plan_sede_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="periodicidad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Diaria", "Diaria"),
                    ("Semanal", "Semanal"),
                    ("Quincenal", "Quincenal"),
                    ("Mensual", "Mensual"),
                    ("Bimestral", "Bimestral"),
                    ("Trimestral", "Trimestral"),
                    ("Semestral", "Semestral"),
                    ("Anual", "Anual"),
                    ("Unica", "Única"),
                    ("Otro", "Otro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="requisitoporempresadetalle",
            name="periodicidad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Diaria", "Diaria"),
                    ("Semanal", "Semanal"),
                    ("Quincenal", "Quincenal"),
                    ("Mensual", "Mensual"),
                    ("Bimestral", "Bimestral"),
                    ("Trimestral", "Trimestral"),
                    ("Semestral", "Semestral"),
                    ("Anual", "Anual"),
                    ("Unica", "Única"),
                    ("Otro", "Otro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
