# Generated by Django 4.2.11 on 2025-05-26 00:42

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_empresa_industria_empresa_paises"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="industria",
            field=models.ForeignKey(
                default=myapp.models.get_default_industria_pk,
                on_delete=django.db.models.deletion.PROTECT,
                to="myapp.industria",
                verbose_name="Industria",
            ),
        ),
    ]
