# Generated by Django 4.2.11 on 2025-05-26 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0012_alter_empresa_industria"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="plan",
            name="myapp_plan_respons_4f09d1_idx",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="responsable_ejecucion",
        ),
        migrations.AddField(
            model_name="plan",
            name="responsables_ejecucion",
            field=models.ManyToManyField(
                blank=True,
                related_name="planes_asignados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsables de Ejecución",
            ),
        ),
    ]
