# Generated by Django 4.2.11 on 2025-05-26 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_remove_plan_myapp_plan_respons_4f09d1_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ejecucionmatriz",
            options={
                "ordering": ["plan"],
                "verbose_name": "Ejecucion del Plan",
                "verbose_name_plural": "Ejecucion de los Planes",
            },
        ),
        migrations.RemoveIndex(
            model_name="ejecucionmatriz",
            name="myapp_ejecu_matriz__81ac72_idx",
        ),
        migrations.AlterUniqueTogether(
            name="ejecucionmatriz",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="ejecucionmatriz",
            name="plan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.plan"
            ),
        ),
        migrations.RemoveField(
            model_name="ejecucionmatriz",
            name="matriz",
        ),
        migrations.RemoveField(
            model_name="ejecucionmatriz",
            name="requisito",
        ),
    ]
